account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/user/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/user/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/user/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/user/password_reset_confirm.html",
            success_url="/account/password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/user/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        TemplateView.as_view(template_name="account/user/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/user/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # wish list
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("account/", include("account.urls", namespace="account")),
    path("order/", include("order.urls", namespace="order")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("order/", views.product_all, name="product_all"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
    path("store/<slug:category_slug>/", views.category_list, name="category_list"),
]

templates/includes/footer.html
<div class="container mt-2">
  <footer class="border-top py-4">
    <div class="row">
      <div class="col-lg-6 col-12 text-center mb-1">
        <span class="text-muted">&copy; 2021 STHLM-foodies, Inc</span>
      </div>
      <div class="col-lg-6 col-12 ">
        <ul class="nav list-unstyled justify-content-center">
          <li class="ms-3"><a class="text-muted" href="https://facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a></li>
          <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram"></i></a></li>
          <li class="ms-3"><a class="text-muted" href="https://twitter.com/" target="_blank"><i class="bi bi-twitter"></i></a></li>
          <li class="ms-3"><a class="text-muted" href="https://www.youtube.com/" target="_blank"><i class="bi bi-youtube"></i></a></li>
          <li class="ms-3"><a class="text-muted" href="https://www.pinterest.com/" target="_blank"><i class="bi bi-pinterest"></i></a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

templates/includes/nav.html
<header class="header">
  <nav class="navbar navbar-expand-md navbar-light bg-light p-2 justify-content-evenly">
    <div class="container-fluid justify-content-center align-items-center text-center">
      <a class="navbar-brand logo d-lg-none d-md-none" href="/">
        STHLM-foodies
      </a>
      <div class="d-flex w-100 navbar-collapse justify-content-center">

        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <i class="bi bi-stack"></i><br>
          <span class="">Menu</span>
        </button>

        {% if user.is_authenticated %}
        <a role="button" href="{% url 'account:dashboard' %}" class="btn btn-outline-secondary border-0 basket-btn d-md-none">
          <div>
            <i class="bi bi-person-circle"></i>
          </div>
          <span class="">{{user.name}}</span>
        </a>
        {% else %}
        <a role="button" href="{% url 'account:dashboard' %}" class="btn btn-outline-secondary border-0 basket-btn d-md-none">
          <div>
            <i class="bi bi-person-circle"></i>
          </div>
          <span class="">Login</span>
        </a>
        {% endif %}


        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
          <div class="navbar-nav mb-lg-0 mx-3">
            <div>
              <a class="nav-link" href="/">
                <i class="bi bi-house-door"></i> <br>
                Home
              </a>
            </div>
            <div>
              <a class="nav-link" href="{% url 'store:product_all' %}">
                <i class="bi bi-egg-fried"></i><br>
                All Products</a>
            </div>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                <i class="bi bi-list"></i> <br>
                <span class="">Categories</span>
              </a>

              <div class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">
                <div class="card border-0">
                  <div class="card-body">
                    <form class="d-flex w-100 d-md-none my-3">
                      <input class="form-control me-2" type="search" placeholder="Search products or FAQ"
                        aria-label="Search">
                      <button class="btn btn-outline-secondary" type="submit">Search</button>
                    </form>
                    <ul class="list-group list-group-flush dropdown-account-link">
                      {% for c in categories %}
                      <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                        <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <a class="nav-link" href="{% url 'store:about' %}">
                <i class="bi bi-suit-heart"></i><br>
                About
              </a>
            </div>
          </div>
        </div>
        <div>
          <div class="collapse navbar-collapse" id="navbarSupportedContent2">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-reset" href="#" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  <div class="small text-muted">
                    {% if user.is_authenticated %}
                    Hello, {{ request.user.name }}
                    {% else %}
                    Login or Register
                    {% endif %}
                  </div>
                  <span class="">Account</span>
                </a>
                <div class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">
                  <div class="card border-0">
                    <div class="card-body">
                      <div class="list-group list-group-flush dropdown-account-link">
                        {% if user.is_authenticated %}
                        <a href="{% url 'account:dashboard' %}"
                          class="text-reset small list-group-item p-0 py-1 border-0 dropdown-account-link">Dashboard</a>
                        <a href="{% url 'account:user_orders' %}"
                          class="text-reset small list-group-item p-0 py-1 border-0 dropdown-account-link">Orders</a>
                        <a href="{% url 'account:wishlist' %}"
                          class="text-reset small list-group-item p-0 py-1 border-0 dropdown-account-link">Wishlist</a>
                        <a href="{% url 'account:logout' %}"
                          class="text-reset small list-group-item p-0 py-1 border-0 dropdown-account-link">Logout</a>
                        {% else %}
                        <a href="{% url 'account:login' %}"
                          class="text-reset small list-group-item p-0 py-1 border-0 dropdown-account-link">Login</a>
                        <a href="{% url 'account:register' %}"
                          class="text-reset small list-group-item p-0 py-1 border-0 dropdown-account-link">Register</a>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <a role="button" href="{% url 'basket:basket_summary' %}" class="btn btn-outline-secondary border-0 basket-btn">
          {% with total_qty=basket|length %}
          <div id="basket-qty" class="basket-qty">
            {% if total_qty > 0 %}
            {{ total_qty }}
            {% else %}
            0
            {% endif %}
          </div>
          {% endwith %}
          <div>
            <i class="bi bi-basket"></i>
          </div>
          {% if basket %}
          <span class="fs15 fw500">£{{basket.get_total_price}}</span>
          {% else %}
          <span class="fs15 fw500">Basket</span>
          {% endif %}
        </a>
      </div>
      <div class="d-md-none d-lg-none d-xl-none">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav me-auto mb-2 mb-md-0">
            <form class="d-flex w-100 d-md-none my-3">
              <input class="form-control me-2" type="search" placeholder="Search products or FAQ" aria-label="Search">
              <button class="btn btn-outline-secondary" type="submit">Search</button>
            </form>
            <div><a class="dropdown-item" href="{% url 'store:product_all' %}">
                <p class="card-title">All Products</p>
              </a>
            </div>
            {% for c in categories %}
            <div {% if category.slug == c.slug %}class="selected" {% endif %}>
              <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
            </div>
            {% endfor %}
          </div>
          <hr>
          <div class="list-group list-group-flush dropdown-account-link">
            {% if user.is_authenticated %}
            <a href="{% url 'account:dashboard' %}" class="dropdown-item">Dashboard</a>
            <a href="{% url 'account:user_orders' %}" class="dropdown-item">Orders</a>
            <a href="{% url 'account:logout' %}" class="dropdown-item">Logout</a>
            {% else %}
            <a href="{% url 'account:login' %}" class="dropdown-item">Login</a>
            <a href="{% url 'account:register' %}" class="dropdown-item">Register</a>
            {% endif %}
            <hr>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>