basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("account/", include("account.urls", namespace="account")),
    path("order/", include("order.urls", namespace="order")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = "order"

urlpatterns = [
    path("add/", views.add, name="add"),
]

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("order/", views.product_all, name="product_all"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
    path("store/<slug:category_slug>/", views.category_list, name="category_list"),
]

order/models.py
from django.conf import settings
from django.db import models
from store.models import Product


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="order_user")
    full_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    address1 = models.CharField(max_length=250)
    address2 = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country_code = models.CharField(max_length=4, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_paid = models.DecimalField(max_digits=5, decimal_places=2)
    order_key = models.CharField(max_length=200)
    payment_option = models.CharField(max_length=200, blank=True)
    billing_status = models.BooleanField(default=False)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return str(self.created)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="order_items", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """
    Category Table implemented with MPTT.
    """

    name = models.CharField(
        verbose_name=_("Category Name"),
        help_text=_("Required and unique"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(verbose_name=_("Category safe URL"), max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """

    name = models.CharField(
        verbose_name=_("Product Type"),
        help_text=_("Required"),
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    """
    The Product Specification Table contains product
    specification or features for the product types.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    The Product table contining all product items.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    title = models.CharField(
        verbose_name=_("title"),
        help_text=_("Required"),
        max_length=255,
    )
    description = models.TextField(verbose_name=_("description"), help_text=_("Not Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    discount_price = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecificationValue(models.Model):
    """
    The Product Specification Value table holds each of the
    products individual specification or bespoke features.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alternative text"),
        help_text=_("Please add alternative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

order/views.py
from basket.basket import Basket
from django.http.response import JsonResponse
from django.shortcuts import render

from .models import Order, OrderItem


def add(request):
    """
    Add products found in the basket to the order.
    """

    basket = Basket(request)
    if request.POST.get("action") == "post":

        order_key = request.POST.get("order_key")
        user_id = request.user.id
        baskettotal = basket.get_total_price()

        # Check if order exists
        if not Order.objects.filter(order_key=order_key).exists():
            order = Order.objects.create(
                user_id=user_id,
                full_name="name",
                address1="add1",
                address2="add2",
                total_paid=baskettotal,
                order_key=order_key,
            )
            order_id = order.pk

            for item in basket:
                OrderItem.objects.create(
                    order_id=order_id,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["qty"],
                )

        return JsonResponse({"success": "Return something"})


def payment_confirmation(data):
    """
    Displays an order confirmation setting payment status to true.
    """
    Order.objects.filter(order_key=data).update(billing_status=True)


def user_orders(request):
    """
    Collects all orders with payment status set to true and display to user.
    """
    user_id = request.user.id
    return Order.objects.filter(user_id=user_id).filter(billing_status=True)

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def home(request):
    """
    Shows home page.
    """
    products = Product.objects.prefetch_related("product_image").filter(is_active=True)
    return render(request, "home.html", {"products": products})


def about(request):
    """
    Shows about page.
    """
    return render(request, "store/about.html")


def category_list(request, category_slug=None):
    """
    Shows category list for category slug and its descendants.
    """
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(
        category__in=Category.objects.get(name=category_slug).get_descendants(include_self=True)
    )
    return render(
        request,
        "store/category.html",
        {"category": category, "products": products},
    )


def product_all(request):
    """
    Displays all products.
    """
    products = Product.objects.all()
    return render(request, "store/all_products.html", {"products": products})


def product_detail(request, slug):
    """
    Displays a single product detail page.
    """
    product = get_object_or_404(Product, slug=slug, is_active=True)
    return render(request, "store/product_detail.html", {"product": product})

templates/store/about.html
{% extends 'base.html' %} {% load static %} {% block title %}About Us{% endblock %} {% block content %}

<div class="container mt-5">
  <div class="row justify-content-center mt-1">
    <div class="col-sm-12 p-4 text-center">
      <h1>About Us</h1>
      <hr />
      <h3>Heathy food is our lifestyle</h3>
      <p>
        We want to inspire you to a Healthy Lifestyle & with us you can feel confident that we have made all the important choices
        for your Health & our Planet! We carefully select all our products & are happy to choose organic with full control & are
        transparent at all levels! We produce all our food on site & collaborate with several local players. Our fruit &
        vegetables are hand-picked daily by our local greengrocer!
      </p>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-3 col-sm-12">
      <img
        class="img-fluid img-about rounded pb-3"
        src="https://images.pexels.com/photos/7456525/pexels-photo-7456525.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
        alt="greens"
      />
    </div>
    <div class="col-md-3 col-sm-12">
      <img
        class="img-fluid img-about rounded pb-3"
        src="https://images.pexels.com/photos/6097841/pexels-photo-6097841.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
        alt=""
      />
    </div>
    <div class="col-md-3 col-sm-12">
      <img
        class="img-fluid img-about rounded pb-3"
        src="https://images.pexels.com/photos/7456538/pexels-photo-7456538.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
        alt=""
      />
    </div>
    <div class="col-md-3 col-sm-12">
      <img
        class="img-fluid img-about rounded mb-5"
        src="https://images.pexels.com/photos/1580466/pexels-photo-1580466.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
        alt=""
      />
    </div>
  </div>
</div>
{% endblock content %}

templates/store/all_products.html
{% extends "base.html" %}
{% load static %}
{% block title %}All Products{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="album py-5">
      <div class="pb-3">
        <h1 class="h3">Popular</h1>
        <div class="col-12 d-flex justify-content-between">
          <div><b>Popular</b> products purchased</div>
        </div>
        <hr />
      </div>
      {% if not products %}
      <div class="col-12">There are currently no products active <a href="{% url 'store:home' %}">back to homepage.</a></div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card border-0">
            <div class="card-body px-0 text-center">
              <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">
                {% for image in product.product_image.all %} {% if image.is_feature%}
                <img class="img-fluid" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}" />
                <p class="card-text">{{ product.title }}</p>
              </a>
              <div class="fw-bold mt-1">£{{product.regular_price}}</div>
            </div>
            {% endif %} {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/store/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <title>{% block title %}STHLM-foodies{% endblock %}</title>

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/basket.css' %}" />
  </head>
  <body>
    {% include "./nav.html"%}

    <div class="container-fluid p-0 mb-5">{% block content %} {% endblock content %}</div>

    {% include "./footer.html"%}
  </body>
</html>

templates/store/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}{% if category %}{{ category.name }}{% else%}Products{% endif %}{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">{{ category.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
    <div><b>Popular</b> products purchased</div>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">There are currently no products active <a href="{% url 'store:home' %}">back to homepage.</a></div>
      {% else %}
      <div class="row">
        {% for product in products %}
        <div class="col-lg-3 col-md-4 col-sm-12">
          <div class="card border-0">
            <div class="card-body px-0 text-center">
              <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">
                {% for image in product.product_image.all %} {% if image.is_feature%}
                <img class="img-fluid" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}" />
                <p class="card-text">{{ product.title }}</p>
              </a>
              <div class="fw-bold mt-1">£{{product.regular_price}}</div>
            </div>
          </div>
        </div>
        {% endif %} {% endfor %}
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %} 

templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <title>STHLM-foodies</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% block content %}
    <!-- ------------------- -->
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/store/order.html
{% extends "base.html" %} {% load static %} {% block title %}Order{% endblock %} {% block content %}

<div class="container">
  <div class="row">
    <div class="album py-5">
      <div class="pb-3">
        <h1 class="h3">Popular</h1>
      </div>
      {% if not products %}
      <div class="col-12">There are currently no products active</div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card border-0">
            <div class="card-body px-0 text-center">
              <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">
                {% for image in product.product_image.all %} {% if image.is_feature%}
                <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}" />
                <p class="card-text">{{ product.title }}</p></a
              >
              <div class="fw-bold mt-1">SEK {{product.regular_price}}</div>
            </div>
            {% endif %} {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ product.name }} {% endblock %}
{% block content %}


<div class="container mt-5">
  <div class="row g-3">
    <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
      <div class="d-grid gap-2">
        <div class="d-flex d-flex-inline justify-content-center">
          <div>
            <span class="h3">£{{ product.regular_price }}</span> <br>
            <small class="text-muted small">You can also update {{product.title}} quantity later.</small>
          </div>
          <div class="">
            <label for="select">Qty</label>
            <select id="select" class="h6" style="width: 50px; height: 40px">
              <option value="1" selected>1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
            </select>
          </div>
        </div>
        <hr />
        <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
          Basket</button>
        {% if product.users_wishlist.exists %}
        <a href="{% url 'account:user_wishlist' product.id %}" class="btn btn-outline-danger fw-500" tabindex="-1"
          role="button" aria-disabled="true">Remove from Favorites</a>
        {% else %}
        <a href="{% url 'account:user_wishlist' product.id %}" class="btn btn-outline-primary fw-500" tabindex="-1"
          role="button" aria-disabled="true">Add to Favorites</a>
        {% endif %}
      </div>
    </div>

    <div class="col-md-7 col-lg-7 p-0">
      <div class="mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-12">
            <div class="p-1 text-center">
              <h1 class="mb-0 h2 pe-4 pb-4 ">{{ product.title }}</h1>
              <div class="border">
                {% for image in product.product_image.all %} {% if image.is_feature %}
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ image.image.url }}"
                  alt="{{ image.image.alt_text }}" />
                {% else %}
                <img class="img-fluid d-block-inline pt-3" width="100px" alt="Responsive image"
                  src="{{ image.image.url }}" alt="{{ image.image.alt_text }}" />
                {% endif %} {% endfor %}
                <p class="text-center">{{product.description}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on("click", "#add-button", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $("#add-button").val(),
        productqty: $("#select option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty;
        location.reload();
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>

{% endblock %}