basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

checkout/urls.py
from django.urls import include, path

from . import views

app_name = "checkout"

urlpatterns = [
    path("deliverychoices", views.deliverychoices, name="deliverychoices"),
    path(
        "basket_update_delivery/",
        views.basket_update_delivery,
        name="basket_update_delivery",
    ),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("account/", include("account.urls", namespace="account")),
    path("order/", include("order.urls", namespace="order")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("order/", views.product_all, name="product_all"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
    path("store/<slug:category_slug>/", views.category_list, name="category_list"),
]

basket/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from store.models import Product

from .basket import Basket


def basket_summary(request):
    """
    Displays a basket summary.
    """
    basket = Basket(request)
    return render(request, "basket/basket_summary.html", {"basket": basket})


def basket_add(request):
    """
    Add an item and the selected quantity to the basket.
    """
    basket = Basket(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        product_qty = int(request.POST.get("productqty"))
        product = get_object_or_404(Product, id=product_id)

        basket.add(product=product, qty=product_qty)
        messages.info(request, f"Added {product} to your cart")
        basketqty = basket.__len__()
        return JsonResponse({"qty": basketqty})


def basket_delete(request):
    """
    Removes items from the users basket.
    """
    basket = Basket(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        product = get_object_or_404(Product, id=product_id)
        messages.info(request, f"Removed {product} from your cart")
        return JsonResponse({"qty": basketqty, "subtotal": baskettotal})


def basket_update(request):
    """
    Allows users to updated their basket.
    """
    basket = Basket(request)
    if request.POST.get("action") == "post":
        product_id = int(request.POST.get("productid"))
        product_qty = int(request.POST.get("productqty"))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        product = get_object_or_404(Product, id=product_id)
        messages.info(request, f"Updated {product} quantity in your cart")
        return JsonResponse({"qty": basketqty, "subtotal": baskettotal})

templates/basket/basket_summary.html
{% extends "base.html" %}
{% load static %}
{% block title %}Basket{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-12">
      <h3>Your Basket</h3>
      <div class="col-12 p-0">Update or remove items from your basket</div>
      {% if not basket %}
      <hr>
      <div class="col-12 p-0">Wow so empty here!<a href="{% url 'store:product_all' %}"> Back to products page</a>
      </div>
      {% else %}
    </div>
  </div>
  <hr>
</div>
<div class="container">
  <div class="row g-3">
    <div class="col-12 p-3">
      <div class="d-flex d-flex-inline">
        <div class="pe-3">Order</div>
      </div>
      <div class="text-end">
        <div class="">Sub Total: <div id="subtotal" class="d-inline-flex fw-bold">£{{basket.get_subtotal_price}}</div>
        </div>
      </div>
    </div>
    <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
      <div class="d-grid gap-2 ">
        <a role="button" href="{% url 'checkout:deliverychoices' %}" class="btn btn-success fw-bold">Checkout
          Securely</a>
        <a role="button" href="{% url 'store:product_all' %}" class="btn btn-outline-dark fw-bold">Back
          to Products</a>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 p-0">
      {% for item in basket %}
      {% with product=item.product %}
      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
        <div class="row g-0">
          <div class="col-md-2 d-none d-md-block">
            {% for image in product.product_image.all %}
            {% if image.is_feature%}
            <img class="img-fluid" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
            {% endif %}
            {% endfor %}
          </div>
          <div class="col-md-10 ps-md-3">
            <div class="card-body p-1">
              <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                <p class="card-text pb-3">{{product.title}}</p>
              </a>
              <label for="select{{product.id}}">Qty</label>
              <select id="select{{product.id}}" style="width:50px;height:31px;">
                <option value="" selected disabled hidden>{{item.qty}}</option>
                <option value="">1</option>
                <option value="">2</option>
                <option value="">3</option>
                <option value="">4</option>
              </select>
              <a id="update-button" data-index="{{product.id}}"
                class="btn btn-primary btn-sm update-button text-decoration-none small">Update</a>
              <a id="delete-button" data-index="{{product.id}}"
                class="btn btn-danger btn-sm delete-button text-decoration-none small">Delete</a>
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
  </div>
  {% endif %}
</div>
<script>
  // Delete Item
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

        if (json.qty == 0) {
          total = 0
          subtotal = 0
        } else {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          subtotal = json.subtotal
        }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        location.reload();

      },
      error: function (xhr, errmsg, err) {},
    });
  });

  // Update Item
  $(document).on("click", ".update-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data("index"),
        productqty: $("#select" + prodid + " option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {

        total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("subtotal").innerHTML = json.subtotal;
        location.reload();
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>

{% endblock %}

templates/basket/summary.html
{% extends "base.html" %}
{% load static %}
{% block title %}Basket{% endblock %}
{% block content %}

<section>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h3>Your Basket</h3>
        {% if not basket %}
        <div class="col-12 p-0">Wow so empty here!<a href="{% url 'store:product_all' %}"> Back to products page</a>
        </div>
        <hr>
        {% else %}
      </div>
    </div>
    <hr>
  </div>
  <div class="container">
    <div class="row g-3">
      {% if basket|length == 0 %}
      <div class="col-12">Your basket is empty <a href="{% url 'store:store_home' %}">Shop</a></div>
      {% else %}
      <div class="col-12 p-3 d-flex justify-content-between">
        <div class="d-flex d-flex-inline">
          <div class="pe-3">Order</div>
          <div class="dropdown">
            <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink"
              data-bs-toggle="dropdown" aria-expanded="false">
              Shipping options
              <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"
                class="bi bi-chevron-down" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                  d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
              </svg>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownLink">
              <li class="item small">Next day delivery</li>
              <li class="item small">Premimum delivery</li>
            </ul>
          </div>
        </div>
        <div class="text-end">
          <div class="">Sub Total: <div id="subtotal" class="d-inline-flex fw-bold">£{{basket.get_subtotal_price}}</div>
          </div>
        </div>
      </div>
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
        <div class="d-grid gap-2 ">
          <a role="button" href="{% url 'checkout:deliverychoices' %}" class="btn btn-success fw-bold"
            type="button">Checkout Securely</a>
          <a role="button" href="{% url "store:product_all" %}" class="btn btn-outline-dark fw-bold" type="button">Back
            to Products</a>
        </div>
      </div>
      <div class="col-md-7 col-lg-8 p-0">
        {% for item in basket %}
        {% with product=item.product %}
        <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              {% for image in product.product_image.all %}
              {% if image.is_feature%}
              <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}"
                alt="{{ image.image.alt_text }}">
              {% endif %}
              {% endfor %}
            </div>
            <div class="col-md-10 ps-md-3">
              <div class="card-body p-1">
                <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                  <p class="card-text pb-3">{{product.title}}</p>
                </a>
                <label for="select">Qty</label>
                <select id="select{{product.id}}" style="width:50px;height:31px;">
                  <option value="" selected disabled hidden>{{item.qty}}</option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <a type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-primary btn-sm update-button text-decoration-none small">Update</a>
                <a type="button" id="delete-button" data-index="{{product.id}}"
                  class="btn btn-danger btn-sm delete-button text-decoration-none small">Delete</a>
              </div>
            </div>
          </div>
        </div>
        {% endwith %}
        {% endfor %}
      </div>
      {% endif %}
    </div>
    {% endif %}
  </div>
</section>
<script>
  // Delete Item
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

        if (json.qty == 0) {
          total = 0
          subtotal = 0
        } else {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          subtotal = json.subtotal
        }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        location.reload();

      },
      error: function (xhr, errmsg, err) {},
    });
  });

  // Update Item
  $(document).on("click", ".update-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data("index"),
        productqty: $("#select" + prodid + " option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {

        total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("subtotal").innerHTML = json.subtotal;
        location.reload();
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>

{% endblock %}